spring.application.name=magiclibrary
spring.datasource.url=jdbc:mariadb://localhost:3306/magiclibrary?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=magiclibrary
spring.app.jwt.secret=${JWT_SECRET}
spring.app.jwt.expiration=86400000
spring.app.jwt.expirationRememberMe=604800000
spring.app.security.remember-me.key=${REMEMBER_ME_KEY}
logging.level.root=INFO
logging.level.org.hibernate.SQL=OFF
logging.level.org.hibernate.orm.jdbc.bind=OFF
logging.level.org.springframework.web=INFO